### ISSUE TITLE
Create two routes

### ISSUE THREAD

**Issue by didiercrunch** [EdwinAndrew/vert-x-tutorial#2]
Create two routes.

| route | what |
|:-------|:--------|
| `/r1`  | always returns hello world |
| `r2/*`   | should return what ever the `*` was |

https://vertx.io/preview/docs/vertx-web/java/#_route_order

**Comment by EdwinAndrew** [comment]
Here's the error I got when I tried a simple router. Code can be found in vert-x-web-example branch. ![image](https://user-images.githubusercontent.com/48691226/81344331-98b06000-9084-11ea-8635-c1ffebb38405.png)

**Comment by didiercrunch** [comment]
You are probably missing a dependency.  Can you push what you have on a branch?

**Comment by didiercrunch** [comment]
I see the branch..

**Comment by didiercrunch** [comment]
I have added [netty all](https://mvnrepository.com/artifact/io.netty/netty-all/4.1.49.Final) following this [stackoverflow](https://stackoverflow.com/questions/32329891/vertx-noclassdeffounderror-io-netty-channel-eventloopgroup).  You can `git pull`

**Comment by EdwinAndrew** [comment]
I tried with the new dependency added but still got the same error.

**Comment by didiercrunch** [comment]
you need to refresh your dependencies somehow.  The problem is your ide.
try to "rebuild the project".

Le jeu. 7 mai 2020, à 17 h 23, Edwin Andrew <notifications@github.com> a
écrit :

**Comment by EdwinAndrew** [comment]
Fixed it by updating dependencies using the following: 
`mvn versions:display-dependency-updates`
`mvn versions:use-latest-releases`
Will update POM now.

**Comment by didiercrunch** [comment]
couple of rule of thumb..
1. functions/methods should never be longer then...6 lines of code.  never.
2. a function/method should do a single thing; never more.  The only way to make sure a function does a single thing and not more is by asking yourself the question.. "can I extract a function out of my function", if the answer is yes, your function makes more than one thing.
3. comments are generally speaking bad.  They highlight the fact that you were unable to describe your intent in code, so you turned to comments (that no one will ever read)


Now, take this badass `start` function and extract all sub functions you can find.  Make that code nice and testable.

Pro tip.

use `this::methodName` to replace arrow functions.

**Comment by EdwinAndrew** [comment]
I'm not sure how to convert lambda expressions into a method reference. Is it possible to show an example with this code block?
```
 Route handler1 = router
                .get("/r1")
                .handler(routingContext -> {
                    HttpServerResponse phrase = routingContext.response();
                    phrase.putHeader("content-type", "text/plain");
                    phrase.end("Hello World!");
                });
```

**Comment by didiercrunch** [comment]
You do something like...
```
    
    public void handler(RoutingContext routingContext){ // <- you need a better function name
        // This handler will be called for every request
        HttpServerResponse response = routingContext.response();
        response.putHeader("content-type", "text/plain");

        // Write to the response and end it
        response.end("Hello World from Vert.x-Web!");
    }
    
    @Override
    public void start() {
        HttpServer server = vertx.createHttpServer();

        Router router = Router.router(vertx);

        router.route().handler(this::handler);  // <- no more "lambda"

        server.requestHandler(router).listen(8080);
    }
```

**Comment by EdwinAndrew** [comment]
Also how come it's more preferred to use method reference rather than lambda expressions?

**Comment by didiercrunch** [comment]
1. lambdas are next to impossible to test
2. lambdas cannot be re-used
3. lambdas are not named (code hard to read)


Le ven. 8 mai 2020, à 14 h 06, Edwin Andrew <notifications@github.com> a
écrit :

**Comment by EdwinAndrew** [comment]
I uploaded my code into the second branch but I am struggling to achieve the requirements.

**Comment by didiercrunch** [comment]
You could try something like bellow..

```
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Vertx;
import io.vertx.core.http.HttpServer;
import io.vertx.core.http.HttpServerResponse;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.RoutingContext;

public class HelloVerticle extends AbstractVerticle {

    private void handleR1(RoutingContext routingContext) {
        HttpServerResponse response = routingContext.response();
        response.putHeader("content-type", "text/plain");
        response.end("hello world");
    }

    private void handleR2(RoutingContext routingContext) {
        String word = routingContext.request().getParam("word");
        HttpServerResponse response = routingContext.response();
        response.putHeader("content-type", "text/plain");
        response.end("hello " + word);
    }

    private void setRoutes(Router router) {
        router.get("/r1")
                .handler(this::handleR1);

        router.get("/r2/:word")
                .handler(this::handleR2);
    }

    @Override
    public void start() {
        HttpServer server = vertx.createHttpServer();
        Router router = Router.router(vertx);
        setRoutes(router);
        server.requestHandler(router).listen(6631);
    }

    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        vertx.deployVerticle(new HelloVerticle());
    }
}

```

**Comment by didiercrunch** [comment]
any news?

**Comment by EdwinAndrew** [comment]
My apologies. I was feeling a little under the weather over the weekend. But I did take a look at the code you sent and I get it now. If I'm not mistaken, I believe what my issue was that I was trying to apply method references where the type signature isn't an exact match.

**Comment by didiercrunch** [comment]
nice job! :tada:
