### ISSUE TITLE
Create unit test for HelloVerticle

### ISSUE THREAD

**Issue by didiercrunch** [EdwinAndrew/vert-x-tutorial#5]
Let's create a simple unit test for `HelloVerticle`.  Just create a simple `add` method and create a unit tests that test that `add(1, 1)` returns `2`.

**Comment by EdwinAndrew** [comment]
Updated the Test file and added Junit dependency to POM

**Comment by didiercrunch** [comment]
Let use Junit 5, you are young and junit 5 is trendier right now.

In addition, you function `add` and it should not be.  The difficulty of creating a unit test lays in setup of it; actually, I define good code as code that is easy to test, and code that is easy to test is code where it is easy to get, from scratch, in a position where you can call any public method. 

So, instead of cheating, let's create a real method, not static and create instanciate an object .

https://junit.org/junit5/docs/current/user-guide/

**Comment by EdwinAndrew** [comment]
I dont fully understand what you mean by creating a real method. But I did update the POM to JUnit 5.

**Comment by didiercrunch** [comment]
Good enough
